// packages/vue-app/src/App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
import TheWelcome from "./components/TheWelcome.vue";
import "../../components/dist/templates/main-template/main-template.js";
import "../../components/dist/molecules/card-overview/card-overview";
import "../../components/dist/molecules/cart-product/cart-product";
import "../../components/dist/molecules/product-in-cart/product-in-cart";
import "../../components/dist/molecules/product-in-stock/product-in-stock";
import type { ProductData } from "../../components/dist/_mixins/product";

/**
 * Mock data -> Temporary
 */
const PRODUCT_MOCK: ProductData = {
  id: "1",
  title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
  price: 109.95,
  description:
    "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  category: "men's clothing",
  image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
  rating: {
    rate: 3.9,
    count: 120,
  },
};

/**
 * Static data
 */
const products = [
  PRODUCT_MOCK,
  PRODUCT_MOCK,
  PRODUCT_MOCK,
  PRODUCT_MOCK,
  PRODUCT_MOCK,
].map((product, i) => ({
  ...product,
  /**
   * Make sure each product has a unique ID
   */
  id: i.toString(),
}));
</script>

<template>
  <ov-default-template>
    <section slot="main">
      <ov-card-overview>
        <li v-for="product in products">
          <ov-product-in-stock
            v-bind:product="product"
            amount="1"
          ></ov-product-in-stock>
        </li>
      </ov-card-overview>
    </section>
    <section slot="side">
      <ov-card-overview>
        <li v-for="product in products">
          <ov-cart-product
            v-bind:product="product"
            amount="1"
          ></ov-cart-product>
        </li>
      </ov-card-overview>
    </section>
  </ov-default-template>
</template>

<style scoped></style>

// packages/react-app/src/App.tsx
import { ProductData } from "components/_mixins/product";
import { useState } from "react";
import "./App.css";
import { OvCardOverview } from "./ui-components/OvCardOverview";
import { OvCartProduct } from "./ui-components/OvCartProduct";
import { OvDefaultTemplate } from "./ui-components/OvDefaultTemplate";
import { OvProductInCart } from "./ui-components/OvProductInCart";
import { OvProductInStock } from "./ui-components/OvProductInStock";

type HashMap<T> = Record<string, T>;

/**
 * Keeps track of the amount of each product in ProductsOverview -> Required UI state
 */
const useAmountsLocal = () => {
  const [amounts, setAmounts] = useState<HashMap<number>>({});

  const incrementAmount = (id: string, step: number) =>
    setAmounts((amounts) => ({
      ...amounts,
      [id]: (amounts[id] ?? 1) + step,
    }));

  const decrementAmount = (id: string, step: number) =>
    setAmounts((amounts) => ({
      ...amounts,
      [id]: (amounts[id] ?? 1) - step,
    }));

  return { amounts, incrementAmount, decrementAmount };
};

/**
 * Keeps track of the cart -> Temporary UI state
 */
const useCartLocal = () => {
  const [cart, setCart] = useState<HashMap<boolean>>({});

  const addToCart = (id: string) =>
    setCart((cart) => ({
      ...cart,
      [id]: true,
    }));

  const removeFromCart = (id: string) => {
    setCart((cart) => ({
      ...cart,
      [id]: false,
    }));
  };
  return { cart, addToCart, removeFromCart };
};

/**
 * Mock data -> Temporary
 */
const PRODUCT_MOCK: ProductData = {
  id: "1",
  title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
  price: 109.95,
  description:
    "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  category: "men's clothing",
  image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
  rating: {
    rate: 3.9,
    count: 120,
  },
};

function App() {
  /**
   * Static data
   */
  const products = [
    PRODUCT_MOCK,
    PRODUCT_MOCK,
    PRODUCT_MOCK,
    PRODUCT_MOCK,
    PRODUCT_MOCK,
  ].map((product, i) => ({
    ...product,
    /**
     * Make sure each product has a unique ID
     */
    id: i.toString(),
  }));

  /**
   * UI state amount of each product (before added to the cart)
   */
  const { incrementAmount, decrementAmount, amounts } = useAmountsLocal();

  /**
   * Temporary cart logic
   */
  const { addToCart, removeFromCart, cart } = useCartLocal();

  /**
   *  Overview of products
   */
  const renderProductsOverview = () => (
    <>
      <h2>Products</h2>
      <OvCardOverview>
        {products!.map((product) =>
          !cart[product.id] ? (
            <OvProductInStock
              key={product.id}
              product={product}
              amount={amounts[product.id] ?? 1}
              onIncrement={({ detail: { step } }) =>
                incrementAmount(product.id, step)
              }
              onDecrement={({ detail: { step } }) =>
                decrementAmount(product.id, step)
              }
              onAddToCart={() => addToCart(product.id)}
            ></OvProductInStock>
          ) : (
            <OvProductInCart
              key={product.id}
              product={product}
              onRemoveFromCart={() => {
                removeFromCart(product.id);
              }}
            ></OvProductInCart>
          )
        )}
      </OvCardOverview>
    </>
  );

  /**
   *  Cart
   */
  const renderCart = () => (
    <>
      <OvCardOverview>
        {products
          .filter((product) => cart[product.id])!
          .map((product) => (
            <OvCartProduct
              key={product.id}
              product={product}
              amount={amounts[product.id] ?? 1}
              onRemoveFromCart={() => {
                removeFromCart(product.id);
              }}
              onIncrement={({ detail: { step } }) =>
                incrementAmount(product.id, step)
              }
              onDecrement={({ detail: { step } }) =>
                decrementAmount(product.id, step)
              }
            ></OvCartProduct>
          ))}
      </OvCardOverview>
    </>
  );

  return (
    <OvDefaultTemplate>
      <section slot="main">{renderProductsOverview()}</section>
      <section slot="side">{renderCart()}</section>
    </OvDefaultTemplate>
  );
}

export default App;
